# Generated by Django 5.0 on 2023-12-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
