# Generated by Django 5.0 on 2023-12-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_journal_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journal_Image',
            new_name='Image_Journal',
        ),
    ]
