# Generated by Django 5.0 on 2023-12-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_rename_journal_image_image_journal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_Journal',
        ),
    ]
