# Generated by Django 5.0 on 2023-12-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_delete_image_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
